title: hateoflux Documentation
description: Documentation of the HATEOAS-Webflux library hateoflux
theme: just-the-docs

url: https://just-the-docs.github.io


logo: "/assets/logos/hateoflux_black.svg"
favicon_ico: "/assets/logos/hf_dots_favicon.ico"
color_scheme: wider
back_to_top: true
back_to_top_text: "Back to top"